package groupe6.ldveh;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import groupe6.ldveh.model.json.JSONParser;

/**
 * JavaFX App
 */
public class App{

    /**private static Scene scene;

    @Override
    public void start(Stage stage) throws IOException {
        scene = new Scene(loadFXML("primary"), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    static void setRoot(String fxml) throws IOException {
        scene.setRoot(loadFXML(fxml));
    }

    private static Parent loadFXML(String fxml) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource(fxml + ".fxml"));
        return fxmlLoader.load();
    }

    public static void main(String[] args) {
        launch();
    }*/
	
	public static void main(String[] args) {
		String str = "  {\r\n"
				+ "    \"world\": \"Sylvarant\",\r\n"
				+ "    \"places\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\":1,\r\n"
				+ "        \"name\": \"Iselia\",\r\n"
				+ "        \"description\": \"Un village paisible où les aventuriers commencent leur voyage.\",\r\n"
				+ "        \"start\": true,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\": false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 2,\r\n"
				+ "        \"name\": \"Temple de Martel\",\r\n"
				+ "        \"description\": \"Un lieu sacré dédié à la déesse Martel.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": {\r\n"
				+ "          \"name\": \"Martel\",\r\n"
				+ "          \"HP\": 150,\r\n"
				+ "          \"Armor\": 50,\r\n"
				+ "          \"Attack\": 30\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 3,\r\n"
				+ "        \"name\": \"Triet\",\r\n"
				+ "        \"description\": \"Une petite oasis dans le désert, réputée pour son marché animé.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 4,\r\n"
				+ "        \"name\": \"Desert de Triet\",\r\n"
				+ "        \"description\": \"Un désert aride avec des tempêtes de sable imprévisibles.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": {\r\n"
				+ "          \"name\": \"\",\r\n"
				+ "          \"HP\": 180,\r\n"
				+ "          \"Armor\": 70,\r\n"
				+ "          \"Attack\": 40\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 5,\r\n"
				+ "        \"name\": \"Forêt de Gaoracchia\",\r\n"
				+ "        \"description\": \"Une forêt dense et mystérieuse, facile de s'y perdre.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 6,\r\n"
				+ "        \"name\": \"Ruines de Balacruf\",\r\n"
				+ "        \"description\": \"Anciennes ruines où reposent de nombreux mystères.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 7,\r\n"
				+ "        \"name\": \"Fjord de Thoda\",\r\n"
				+ "        \"description\": \"Un lieu glacial où le vent souffle constamment.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": {\r\n"
				+ "          \"name\": \"Thoda\",\r\n"
				+ "          \"HP\": 200,\r\n"
				+ "          \"Armor\": 60,\r\n"
				+ "          \"Attack\": 35\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 8,\r\n"
				+ "        \"name\": \"Palmacosta\",\r\n"
				+ "        \"description\": \"Une ville portuaire prospère et commerçante.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 9,\r\n"
				+ "        \"name\": \"tour du Salut\",\r\n"
				+ "        \"description\": \"Une tour mystique visible à des kilomètres, elle inspire crainte et respect.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": true,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 10,\r\n"
				+ "        \"name\": \"Mont Fooji\",\r\n"
				+ "        \"description\": \"Une montagne dangereuse avec des pentes escarpées.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": {\r\n"
				+ "          \"name\": \"Fooji\",\r\n"
				+ "          \"HP\": 250,\r\n"
				+ "          \"Armor\": 80,\r\n"
				+ "          \"Attack\": 45\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 11,\r\n"
				+ "        \"name\": \"Temple du Vent\",\r\n"
				+ "        \"description\": \"Un temple situé au sommet d'une montagne où le vent est omniprésent.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 12,\r\n"
				+ "        \"name\": \"Vallée de Hakonesia\",\r\n"
				+ "        \"description\": \"Une vallée mystérieuse entourée de montagnes.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 13,\r\n"
				+ "        \"name\": \"Asgard\",\r\n"
				+ "        \"description\": \"Une ville ancienne connue pour ses ruines et son histoire riche.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 14,\r\n"
				+ "        \"name\": \"Lac Umacy\",\r\n"
				+ "        \"description\": \"Un lac sacré avec des eaux cristallines.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": {\r\n"
				+ "          \"name\": \"\",\r\n"
				+ "          \"HP\": 170,\r\n"
				+ "          \"Armor\": 55,\r\n"
				+ "          \"Attack\": 28\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 15,\r\n"
				+ "        \"name\": \"Mizuho\",\r\n"
				+ "        \"description\": \"Un village caché où les ninjas s'entraînent.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 16,\r\n"
				+ "        \"name\": \"Temple de la Foudre\",\r\n"
				+ "        \"description\": \"Un temple dangereux où des éclairs frappent constamment. Vous avez été foudroyé, vous mourrez.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  true,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 17,\r\n"
				+ "        \"name\": \"Heimdall\",\r\n"
				+ "        \"description\": \"Le village caché des elfes.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": {\r\n"
				+ "          \"name\": \"Presea\",\r\n"
				+ "          \"HP\": 220,\r\n"
				+ "          \"Armor\": 75,\r\n"
				+ "          \"Attack\": 50\r\n"
				+ "        }\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 18,\r\n"
				+ "        \"name\": \"Forêt de Ymir\",\r\n"
				+ "        \"description\": \"Une forêt enchantée où la nature est vivante.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 19,\r\n"
				+ "        \"name\": \"Temple du Feu\",\r\n"
				+ "        \"description\": \"Un temple brûlant où le feu est omniprésent.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 20,\r\n"
				+ "        \"name\": \"Flanoir\",\r\n"
				+ "        \"description\": \"Un village enneigé et isolé au nord.\",\r\n"
				+ "        \"start\": false,\r\n"
				+ "        \"end\": false,\r\n"
				+ "        \"defeat\":  false,\r\n"
				+ "        \"monster\": null\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"paths\": [\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 1,\r\n"
				+ "        \"secondPlace\": 2,\r\n"
				+ "        \"distance\": 5\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 1,\r\n"
				+ "        \"secondPlace\": 3,\r\n"
				+ "        \"distance\": 4\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 1,\r\n"
				+ "        \"secondPlace\": 5,\r\n"
				+ "        \"distance\": 8\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 2,\r\n"
				+ "        \"secondPlace\": 4,\r\n"
				+ "        \"distance\": 7\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 2,\r\n"
				+ "        \"secondPlace\": 6,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 2,\r\n"
				+ "        \"secondPlace\": 7,\r\n"
				+ "        \"distance\": 10\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 3,\r\n"
				+ "        \"secondPlace\": 4,\r\n"
				+ "        \"distance\": 6\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 3,\r\n"
				+ "        \"secondPlace\": 8,\r\n"
				+ "        \"distance\": 12\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 3,\r\n"
				+ "        \"secondPlace\": 9,\r\n"
				+ "        \"distance\": 5\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 4,\r\n"
				+ "        \"secondPlace\": 6,\r\n"
				+ "        \"distance\": 7\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 4,\r\n"
				+ "        \"secondPlace\": 10,\r\n"
				+ "        \"distance\": 14\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 4,\r\n"
				+ "        \"secondPlace\": 11,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 5,\r\n"
				+ "        \"secondPlace\": 6,\r\n"
				+ "        \"distance\": 4\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 5,\r\n"
				+ "        \"secondPlace\": 9,\r\n"
				+ "        \"distance\": 10\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 5,\r\n"
				+ "        \"secondPlace\": 12,\r\n"
				+ "        \"distance\": 8\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 6,\r\n"
				+ "        \"secondPlace\": 7,\r\n"
				+ "        \"distance\": 6\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 6,\r\n"
				+ "        \"secondPlace\": 13,\r\n"
				+ "        \"distance\": 15\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 7,\r\n"
				+ "        \"secondPlace\": 8,\r\n"
				+ "        \"distance\": 11\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 7,\r\n"
				+ "        \"secondPlace\": 10,\r\n"
				+ "        \"distance\": 13\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 7,\r\n"
				+ "        \"secondPlace\": 14,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 8,\r\n"
				+ "        \"secondPlace\": 9,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 8,\r\n"
				+ "        \"secondPlace\": 15,\r\n"
				+ "        \"distance\": 14\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 9,\r\n"
				+ "        \"secondPlace\": 11,\r\n"
				+ "        \"distance\": 5\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 9,\r\n"
				+ "        \"secondPlace\": 16,\r\n"
				+ "        \"distance\": 11\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 10,\r\n"
				+ "        \"secondPlace\": 11,\r\n"
				+ "        \"distance\": 12\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 10,\r\n"
				+ "        \"secondPlace\": 17,\r\n"
				+ "        \"distance\": 10\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 11,\r\n"
				+ "        \"secondPlace\": 12,\r\n"
				+ "        \"distance\": 6\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 11,\r\n"
				+ "        \"secondPlace\": 18,\r\n"
				+ "        \"distance\": 15\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 12,\r\n"
				+ "        \"secondPlace\": 13,\r\n"
				+ "        \"distance\": 10\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 12,\r\n"
				+ "        \"secondPlace\": 19,\r\n"
				+ "        \"distance\": 13\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 13,\r\n"
				+ "        \"secondPlace\": 14,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 13,\r\n"
				+ "        \"secondPlace\": 17,\r\n"
				+ "        \"distance\": 8\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 14,\r\n"
				+ "        \"secondPlace\": 15,\r\n"
				+ "        \"distance\": 6\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 14,\r\n"
				+ "        \"secondPlace\": 20,\r\n"
				+ "        \"distance\": 7\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 15,\r\n"
				+ "        \"secondPlace\": 16,\r\n"
				+ "        \"distance\": 10\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 15,\r\n"
				+ "        \"secondPlace\": 18,\r\n"
				+ "        \"distance\": 11\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 16,\r\n"
				+ "        \"secondPlace\": 17,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 16,\r\n"
				+ "        \"secondPlace\": 19,\r\n"
				+ "        \"distance\": 12\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 17,\r\n"
				+ "        \"secondPlace\": 18,\r\n"
				+ "        \"distance\": 8\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 17,\r\n"
				+ "        \"secondPlace\": 20,\r\n"
				+ "        \"distance\": 14\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 18,\r\n"
				+ "        \"secondPlace\": 19,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 18,\r\n"
				+ "        \"secondPlace\": 20,\r\n"
				+ "        \"distance\": 5\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 19,\r\n"
				+ "        \"secondPlace\": 20,\r\n"
				+ "        \"distance\": 7\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 6,\r\n"
				+ "        \"secondPlace\": 14,\r\n"
				+ "        \"distance\": 10\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 10,\r\n"
				+ "        \"secondPlace\": 15,\r\n"
				+ "        \"distance\": 9\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"firstPlace\": 3,\r\n"
				+ "        \"secondPlace\": 16,\r\n"
				+ "        \"distance\": 13\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "";
		JSONParser parser = new JSONParser(str);
		Object obj = parser.parseObject();
		System.out.println(obj.toString());
	}

}